### ISSUE TITLE
[HttpFoundation]  Symfony API documentation is missing RedisSessionHandler class in 4.1

### ISSUE THREAD

**Issue by alenpokos** [symfony/symfony-docs#10011]
The Symfony API documentation for HttpFoundation is missing RedisSessionHandler class in 4.1, link:
https://api.symfony.com/4.1/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.html

The class is in 4.1, github link:
https://github.com/symfony/http-foundation/blob/4.1/Session/Storage/Handler/RedisSessionHandler.php

The documentation links to 404 page for RedisSessionHandler from https://symfony.com/doc/current/components/http_foundation/session_configuration.html#custom-save-handlers

**Comment by DPerkunas** [comment]
Bump on this. Want to use this feature, but no info on how.

**Comment by michaelperrin** [comment]
@DPerkunas I wrote this article on the use of the `RedisSessionHandler` class: http://blog.michaelperrin.fr/2018/08/14/redis-session-handling-in-symfony/

I tried to figure out why there is a 404 page from the documentation (as I had the same problem), but could not understand why.

**Comment by DPerkunas** [comment]
You’re awesome, thank you for taking the time to write it up. I’ll try it out.

**Comment by michaelperrin** [comment]
You're welcome!

I think that the 404 error page is on Sensio's side.

On the meantime, maybe I could transpose my article for a new Symfony documentation entry, just like the one for [PDO](http://symfony.com/doc/current/doctrine/pdo_session_storage.html). What do you think @javiereguiluz @weaverryan?

**Comment by DPerkunas** [comment]
Checking back in, it's working great. The only issue I'm having is when installing new stuff via composer, cache fails to clear and gives me the following error. 

It only occurs during composer installs, if I do php bin/console cache:clear, no issues. 

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Redis" from the global namespace.
!!  Did you forget a "use" statement? in /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php:669
!!  Stack trace:
!!  #0 /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php(509): ContainerQy0GG7I\srcDevDebugProjectContainer->getDoctrineCache_Providers_Doctrine_Orm_DefaultResultCacheService()
!!  #1 /Users/myname/project/vendor/symfony/dependency-injection/Container.php(242): ContainerQy0GG7I\srcDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()
!!  #2 /Users/myname/project/vendor/symfony/dependency-injection/Container.php(222): Symfony\Component\DependencyInjection\Container->make('doctrine.orm.de...', 1)
!!  #3 /Users/myname/project/vendor/symfony/doctrine-bridge/ManagerRegistry.php(35): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')
!!  #4 /Users/myname/project/v in /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php on line 669
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Redis" from the global namespace.
!!  Did you forget a "use" statement? in /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php:669
!!  Stack trace:
!!  #0 /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php(509): ContainerQy0GG7I\srcDevDebugProjectContainer->getDoctrineCache_Providers_Doctrine_Orm_DefaultResultCacheService()
!!  #1 /Users/myname/project/vendor/symfony/dependency-injection/Container.php(242): ContainerQy0GG7I\srcDevDebugProjectContainer->getDoctrine_Orm_DefaultEntityManagerService()
!!  #2 /Users/myname/project/vendor/symfony/dependency-injection/Container.php(222): Symfony\Component\DependencyInjection\Container->make('doctrine.orm.de...', 1)
!!  #3 /Users/myname/project/vendor/symfony/doctrine-bridge/ManagerRegistry.php(35): Symfony\Component\DependencyInjection\Container->get('doctrine.orm.de...')
!!  #4 /Users/myname/project/v in /Users/myname/project/var/cache/dev/ContainerQy0GG7I/srcDevDebugProjectContainer.php on line 669
!!  

```

**Comment by michaelperrin** [comment]
It looks likes you are running Composer outside of your PHP installation which has the Redis extension installed (e.g. you are running Composer on your host system while your PHP installation is in a Docker container).
The solution is to run Composer in the Docker container.
