### ISSUE TITLE
All doc versions: "app.(a hash).js:24 Uncaught TypeError: Cannot read property 'autocomplete' of undefined"

### ISSUE THREAD

**Issue by ericpoe** [symfony/symfony-docs#10028]
As a result of the above error (seen in the console tab of web dev tools), all pages say, "WARNING: You are browsing the documentation for Symfony " {version} " which is not maintained anymore. Consider upgrading your projects to Symfony 4.1." Here, "version" might be "2.8" or "4.1" or "3.4" or somewhere in between.
<img width="735" alt="screen shot 2018-07-06 at 8 30 10 pm" src="https://user-images.githubusercontent.com/1981351/42405514-f32dcefc-815c-11e8-9d92-e80e0da0c1e0.png">

See: 
- http://symfony.com/doc/2.8/page_creation.html
- http://symfony.com/doc/3.4/page_creation.html
- http://symfony.com/doc/4.1/page_creation.html
- http://symfony.com/doc/current/page_creation.html

Additional info in Chrome's DevTools:

```
jQuery.Deferred exception: Cannot read property 'autocomplete' of undefined TypeError: Cannot read property 'autocomplete' of undefined
    at Object.bindSearch (https://connect.sensiolabs.com/sln.js?customize_url=http://symfony.com/sln_customiser.js:193:45)
    at Object.bindEvents (https://connect.sensiolabs.com/sln.js?customize_url=http://symfony.com/sln_customiser.js:161:18)
    at HTMLDocument.<anonymous> (<anonymous>:40:12)
    at l (http://symfony.com/build/js/app.688dd615bbeb331a3e91.js:24:25137)
    at c (http://symfony.com/build/js/app.688dd615bbeb331a3e91.js:24:25451) undefined
```

**Comment by javiereguiluz** [comment]
This JavaScript error was finally solved, so we can close this issue. Thanks.
