### ISSUE TITLE
Epub: TemplateAssertionError: no test named 'index' (2.8)

### ISSUE THREAD

**Issue by jacekpl** [symfony/symfony-docs#5707]
I get error below while trying to generate epub file:

```
# Sphinx version: 1.3.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  0%] best_practices/business-logic
# Loaded extensions:
#   sensio.sphinx.phpcode (unknown version) from /Library/Python/2.7/site-packages/sensio/sphinx/phpcode.pyc
#   sphinx.ext.autodoc (1.3.1) from /Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/ext/autodoc.pyc
#   sensio.sphinx.configurationblock (unknown version) from /Library/Python/2.7/site-packages/sensio/sphinx/configurationblock.pyc
#   sphinx.ext.doctest (1.3.1) from /Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/ext/doctest.pyc
#   alabaster (0.7.6) from /Library/Python/2.7/site-packages/alabaster-0.7.6-py2.7.egg/alabaster/__init__.pyc
#   sensio.sphinx.bestpractice (unknown version) from /Library/Python/2.7/site-packages/sensio/sphinx/bestpractice.pyc
#   sensio.sphinx.refinclude (unknown version) from /Library/Python/2.7/site-packages/sensio/sphinx/refinclude.pyc
#   symfonycom.sphinx (unknown version) from /Users/jacek/Downloads/symfony-docs/_theme/_exts/symfonycom/sphinx/__init__.pyc
#   sphinx.ext.todo (1.3.1) from /Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/ext/todo.pyc
#   sensio.sphinx.codeblock (unknown version) from /Library/Python/2.7/site-packages/sensio/sphinx/codeblock.pyc
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/__init__.py", line 362, in _write_serial
    self.write_doc(docname, doctree)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/epub.py", line 378, in write_doc
    return StandaloneHTMLBuilder.write_doc(self, docname, doctree)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/html.py", line 445, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/epub.py", line 465, in handle_page
    outfilename, event_arg)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/builders/html.py", line 786, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Library/Python/2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jacek/Downloads/symfony-docs/_theme/_templates/layout.html", line 6, in <module>
    {% set isIndex = pagename is index %}
TemplateAssertionError: no test named 'index'
```

Any hints regarding that?

**Comment by AndoniZubimendi** [comment]
I have the same problem building the epub.

In the meantime you can comment ```templates_path = ['_theme/_templates']``` in ```conf.py``` to build the epub without using the new templates.

**Comment by WouterJ** [comment]
The `index` test used in the new template is created by the symfonycom extension: https://github.com/symfony/symfony-docs/blob/2.8/_theme/_exts/symfonycom/sphinx/__init__.py#L25

This is done in the HTMLTranslator class, which of course isn't used by the epub builder. For some reason though, the epub builder tries to use the new symfony.com theme. I'll look for a way to extract the code from the HTMLTranslator to a more generic class, not very confident if it's possible though (as the current code already is kind of a hack).

**Comment by jacekpl** [comment]
Any news regarding that one? I'm still not able to create an epub file. Error message:
Exception occurred:
  File "/Users/jacek/Downloads/symfony-docs/_theme/_templates/layout.html", line 6, in <module>
    {% set isIndex = pagename is index %}
TemplateAssertionError: no test named 'index'

I have updated all needed extensions.

**Comment by renoirb** [comment]
Same issue here with v 3.0 docs.

Platform:
* Mac OS X 10.11.12
* Python w/ Virtualenv Wrapper
* `bash`, initialized from `fish`

Steps:

```bash
bash
bash-4.3$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)
// ...
bash-4.3$ mkvirtualenv foo
bash-4.3$ lsvirtualenv
// (some virtualenvs, foo is now part of it)
bash-4.3$ workon foo
(foo)bash-4.3$ python -V
Python 2.7.10
(foo)bash-4.3$ pip list
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)
(foo)bash-4.3$ pip install sphinx~=1.3 git+https://github.com/fabpot/sphinx-php.git
make epub
```

with output

```bash
sphinx-build -b epub -d _build/doctrees   . _build/epub
Running Sphinx v1.3.3
A Translator for the html builder is changed.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 467 source files that are out of date
updating environment: [config changed] 467 added, 0 changed, 0 removed
reading sources... [100%] reference/twig_reference
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  0%] best_practices/business-logic
Exception occurred:
  File "/Users/renoirb/workspaces/sandbox/symfony-docs/symfony-docs/_theme/_templates/layout.html", line 6, in <module>
    {% set isIndex = pagename is index %}
TemplateAssertionError: no test named 'index'
The full traceback has been saved in /var/folders/yd/SOMETHING_RANDOM/T/sphinx-err-SOMETHING_RANDOM.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [epub] Error 1
```

**Comment by renoirb** [comment]
After some more debugging, it seems that `-b epub` doesn't load the same extensions as when we load `-b html`. Removing both `get_type` and `index` Jinja references successfully builds epub version. Will come soon to report more findings.

**Comment by dupuchba** [comment]
still have the issue and done what @renoirb is saying without so much understanding :( ... @renoirb do you have any more insights ?

**Comment by renoirb** [comment]
I abandoned. Sorry about that.

**Comment by xabbuh** [comment]
Unfortunately I am not much of help here too. Since we have the integration with platform.sh I no longer build the documentation locally and didn't invest much time to find a solution for this.

**Comment by dupuchba** [comment]
Ok, it's not that important. I just wanted a cool way to have the docs on my kindle but I can live without it ^^

**Comment by xabbuh** [comment]
I know it's not so nice. In the past I used the PDF documents on Kindle readers too. It's not the best option but it is acceptable. Maybe that works for you too.

**Comment by michaelperrin** [comment]
I could manage to generate the ePub file, adding a line to the `__init__.py` file, as shown in my repository: https://github.com/michaelperrin/symfony-docs/blob/epub-generation/_build/_theme/_exts/symfonycom/sphinx/__init__.py#L168

I have a few issues with the generated ePub file (but I could understand the reasons, and will have a look at it). I will open a PR if I manage to solve the remaining problems and if you think it can be useful.

**Comment by javiereguiluz** [comment]
I'm closing this because we don't provide support for generating docs in ePub format. But you can keep discussing about this in #7347 if you want. Thanks!
