### ISSUE TITLE
create your own framework: dependency injection breaks controller code

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-docs#9371]
on this page https://symfony.com/doc/current/create_framework/dependency_injection.html

when you apply the first two code snippets

* example.com/src/Simplex/Framework.php
* example.com/web/front.php

you get the following error:

```
PHP Fatal error:  Uncaught LogicException: The controller must return a response (Nope, this is not a leap year. given). in example.com/vendor/symfony/http-kernel/HttpKernel.php:165
Stack trace:
#0 example.com/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#1 example.com/web/front.php(12): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#2 {main}
  thrown in example.com/vendor/symfony/http-kernel/HttpKernel.php on line 165
```

**Comment by javiereguiluz** [comment]
@flip111 in the previous chapter (https://symfony.com/doc/current/create_framework/http_kernel_httpkernel_class.html) you can read:

> Now, let's create a listener, one that allows a controller to return a string instead of a full Response object:
>
> To implement this feature, we are going to listen to the kernel.view event, which is triggered just after the controller has been called. Its goal is to convert the controller return value to a proper Response instance, but only if needed:

So, it seems that this is intended (returning a string instead of a `Response` object, but you need to create the mentioned listener). Can you please check if you have the same code shown in https://symfony.com/doc/current/create_framework/http_kernel_httpkernel_class.html? Thanks!

**Comment by flip111** [comment]
I don't have my code anymore since i upgraded all code to include the DI stuff. Sorry about that. But i remember that i had my page working after completing the "kernel class" page. Only when i started on the DI page things started to break.

As you can see on the DI page the `$dispatcher->addSubscriber()` code is changed and put into a `Framework` class. It's not until `Now, here is how you can register a custom listener in the front controller:` on the same page to where the `StringResponseListener` is added back.

The text reads as if applying those two first snippets on the DI page give you the same working code but then rewritten. When talking like `The previous code did not exhibit the same issues because we used dependency injection` .. with "exhibit" i understand actually running the code. But the code is not runnable until the controller is changed or the stringresponselistener is put back.
